services:
  llama_app:
    build: .
    ports:
      - "5000:5000"  # Map Gradio app port
    volumes:
      - ./app:/app       # Mount the project directory for live code updates (optional)
    environment:
      - TRANSFORMERS_CACHE=/app/.cache/huggingface
      - FLASK_ENV=development
    networks:
      - llama_network
  gradio_app:
    build: 
      context: ./gradio
    ports:
      - "7860:7860"
    networks:
      - llama_network

networks:
  llama_network:
    driver: bridge
