services:
  priceprophet-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"  # Map Gradio app port
    volumes:
      - .:/app       # Mount the project directory for live code updates (optional)
    environment:
      - TRANSFORMERS_CACHE=/app/.cache/huggingface

